# Generated by Django 5.2.7 on 2025-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
